[Feature] 위젯 > 위젯 구현하기 #9
Dont-forget6/Dont-Forget pull request #17
Opened 2023-10-14 16:35 UTC by JUNGCHAEYOON

## 🔎 What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Optimization
- [ ] Documentation Update
- [ ] Other... Please describe:

## 🐥 What need this change? 

- Related Issues : [Feature] 위젯 > 위젯 구현하기 #9
- Closes : [Feature] 위젯 > 위젯 구현하기 #9

## 📝 Changes 
위젯 기능추가
* 이미지 파일 선택( flaticon 무료 연필 이미지 사진임시로 사용)
* 클릭시 바로 글쓰기로 이동하는 부분 구현 어렵다고 판단하여 mainAcitivity 실행까지만 구현

## 📷 Screenshots, Recordings (optional)

## 👫 To Reviewers (optional)

2023-10-15 02:21 UTC, dkin12 approved these changes
mainActivity로 밖에 변경 안 되는 건가요? 일단 확인했습니다!

2023-10-15 10:42 UTC, JUNGCHAEYOON commented
> mainActivity로 밖에 변경 안 되는 건가요? 일단 확인했습니다!

넵.. mainActivity 에서 AddFragment로 이동하는 동작을 넣으려고 MyApplication에 공통변수를 두고 위젯을 클릭시에 해당 변수를 변경해서 main에서 바로 넘어가게 하려고 시도했는데

onUpdate 가 onCreate와는 다르게 클릭해도 해당 코틀린 파일로 바로 접근하는방식이 아니어서 30분마다 한번만 글쓰기 화면으로 이동되도록 구현이 되더라고요...

그래서 activity를 실행하는 것 까지만 가능한것 같습니다

2023-10-17 07:19 UTC, PIYUJIN requested changes
저번에 이야기했던 위젯 설정시 아이콘이 보이지 않는 현상 해결하고 다시 feature/widget 브랜치에 커밋 올려주세요! 다시 PR 안보내고 기존 branch에 커밋, 푸시만 해주시면 됩니다!

2023-10-17 07:19 UTC, PIYUJIN commented on DontForget/app/src/main/java/com/test/dontforget/UI/widget/AppWidget.kt
실제로 사용할 아이콘 제작해서 그걸로 수정하고 테스트 해보면 좋을 것 같습니다. 현재 아이콘이 잘 안보이는 현상이요!

2023-10-17 07:19 UTC, PIYUJIN commented on DontForget/app/src/main/res/values/dimens.xml
이건 혹시 사용하고 계시는 margin 값인가요? 사용 안하시는 거면 지워도 될 것 같습니다!

2023-10-20 00:16 UTC, JUNGCHAEYOON commented on DontForget/app/src/main/res/values/dimens.xml
앱 위젯 만들때 자동으로 추가된 값인가 보네요 삭제하겠습니다.

2023-10-22 15:08 UTC, PIYUJIN commented on DontForget/app/src/main/res/values/dimens.xml
삭제하고 바로 여기 브랜치로 올려주세요!

2023-10-25 01:16 UTC, PIYUJIN approved these changes

2023-10-25 01:23 UTC, closed without merging